// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLYynizEraEcr_O1pN3qUynMiHezwcaNQ',
    appId: '1:882697319916:web:11d93a42c0b6a9ac59fcc9',
    messagingSenderId: '882697319916',
    projectId: 'advanced-store-app',
    authDomain: 'advanced-store-app.firebaseapp.com',
    storageBucket: 'advanced-store-app.appspot.com',
    measurementId: 'G-DJE3V6KFGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSXSuGAcbPnbjp3b640Zz4DVQ5W54eIns',
    appId: '1:882697319916:android:a0b3167a9f06bc9659fcc9',
    messagingSenderId: '882697319916',
    projectId: 'advanced-store-app',
    storageBucket: 'advanced-store-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPN3PfIBwxkG5AodE3q-CEMerCiFQVN0o',
    appId: '1:882697319916:ios:89dafb100592c37159fcc9',
    messagingSenderId: '882697319916',
    projectId: 'advanced-store-app',
    storageBucket: 'advanced-store-app.appspot.com',
    iosBundleId: 'com.example.advancedStoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPN3PfIBwxkG5AodE3q-CEMerCiFQVN0o',
    appId: '1:882697319916:ios:89dafb100592c37159fcc9',
    messagingSenderId: '882697319916',
    projectId: 'advanced-store-app',
    storageBucket: 'advanced-store-app.appspot.com',
    iosBundleId: 'com.example.advancedStoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLYynizEraEcr_O1pN3qUynMiHezwcaNQ',
    appId: '1:882697319916:web:0016a47085d872be59fcc9',
    messagingSenderId: '882697319916',
    projectId: 'advanced-store-app',
    authDomain: 'advanced-store-app.firebaseapp.com',
    storageBucket: 'advanced-store-app.appspot.com',
    measurementId: 'G-KWFHKNQSER',
  );
}
